name       : libmad
version    : 0.15.1b
release    : 4
source     :
    - http://downloads.sourceforge.net/project/mad/libmad/0.15.1b/libmad-0.15.1b.tar.gz : bbfac3ed6bfbc2823d3775ebb931087371e142bb0e9bb1bee51a76a6e0078690
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : High-quality MPEG audio decoder.
description: |
    High-quality MPEG audio decoder. It supports MPEG-1 and the MPEG-2 extension to lower sampling frequencies, as well as the de facto MPEG 2.5 format. All three audio layers — Layer I, Layer II, and Layer III (i.e. MP3) — are fully implemented.
optimize   : speed
setup      : |
    %apply_patches
    %configure --disable-debugging --disable-static
build      : |
    %make
install    : |
    %make_install
